from core.scripts_common import (
    ScriptsStatus,
    check_update_all_initialized,
    check_update_all_initialized_local,
    ensure_local_scripts_dir,
    ensure_remote_scripts_dir,
    get_scripts_status,
    get_scripts_status_local,
    get_static_wallpaper_saved_selection,
    get_static_wallpaper_saved_selection_local,
    get_static_wallpaper_state,
    get_static_wallpaper_state_local,
    has_static_wallpaper_saved_selection,
    has_static_wallpaper_saved_selection_local,
    is_ftp_save_sync_service_enabled,
    is_ftp_save_sync_service_enabled_local,
    is_static_wallpaper_active,
    is_static_wallpaper_active_local,
    open_scripts_folder_local,
    open_scripts_folder_on_host,
    reload_mister_menu,
)

from core.scripts_update_all import (
    ensure_update_all_config_bootstrap,
    ensure_update_all_config_bootstrap_local,
    install_update_all,
    install_update_all_local,
    run_update_all_stream,
    uninstall_update_all,
    uninstall_update_all_local,
)

from core.scripts_zaparoo import (
    disable_zaparoo_service_local,
    enable_zaparoo_service,
    enable_zaparoo_service_local,
    get_zaparoo_update_status,
    get_zaparoo_update_status_local,
    install_zaparoo,
    install_zaparoo_local,
    uninstall_zaparoo,
    uninstall_zaparoo_local,
)

from core.scripts_migrate_sd import (
    install_migrate_sd,
    install_migrate_sd_local,
    uninstall_migrate_sd,
    uninstall_migrate_sd_local,
)

from core.scripts_cifs_mount import (
    install_cifs_mount,
    install_cifs_mount_local,
    load_cifs_config,
    load_cifs_config_local,
    remove_cifs_config,
    remove_cifs_config_local,
    run_cifs_mount,
    run_cifs_umount,
    save_cifs_config,
    save_cifs_config_local,
    test_cifs_connection,
    uninstall_cifs_mount,
    uninstall_cifs_mount_local,
)

from core.scripts_auto_time import (
    install_auto_time,
    install_auto_time_local,
    uninstall_auto_time,
    uninstall_auto_time_local,
)

from core.scripts_cd_game_organizer import (
    install_cd_game_organizer,
    install_cd_game_organizer_local,
    uninstall_cd_game_organizer,
    uninstall_cd_game_organizer_local,
)

from core.scripts_dav_browser import (
    install_dav_browser,
    install_dav_browser_local,
    load_dav_browser_config,
    load_dav_browser_config_local,
    remove_dav_browser_config,
    remove_dav_browser_config_local,
    save_dav_browser_config,
    save_dav_browser_config_local,
    uninstall_dav_browser,
    uninstall_dav_browser_local,
)

from core.scripts_ftp_save_sync import (
    disable_ftp_save_sync_service,
    disable_ftp_save_sync_service_local,
    enable_ftp_save_sync_service,
    enable_ftp_save_sync_service_local,
    ensure_ftp_save_sync_bootstrap,
    ensure_ftp_save_sync_bootstrap_local,
    install_ftp_save_sync,
    install_ftp_save_sync_local,
    load_ftp_save_sync_config,
    load_ftp_save_sync_config_local,
    remove_ftp_save_sync_config,
    remove_ftp_save_sync_config_local,
    save_ftp_save_sync_config,
    save_ftp_save_sync_config_local,
    uninstall_ftp_save_sync,
    uninstall_ftp_save_sync_local,
)

from core.scripts_static_wallpaper import (
    apply_static_wallpaper,
    apply_static_wallpaper_local,
    get_static_wallpaper_preview_bytes,
    get_static_wallpaper_preview_bytes_local,
    install_static_wallpaper,
    install_static_wallpaper_local,
    list_static_wallpapers,
    list_static_wallpapers_local,
    remove_static_wallpaper,
    remove_static_wallpaper_local,
    uninstall_static_wallpaper,
    uninstall_static_wallpaper_local,
)

from core.scripts_syncthing import (
    disable_syncthing_start_on_boot,
    disable_syncthing_start_on_boot_local,
    enable_syncthing_start_on_boot,
    enable_syncthing_start_on_boot_local,
    get_syncthing_status,
    get_syncthing_status_local,
    install_syncthing,
    install_syncthing_local,
    is_syncthing_running,
    is_syncthing_start_on_boot_enabled,
    is_syncthing_start_on_boot_enabled_local,
    start_syncthing,
    stop_syncthing,
    toggle_syncthing_start_on_boot,
    toggle_syncthing_start_on_boot_local,
    uninstall_syncthing,
    uninstall_syncthing_local,
)

from core.scripts_ra_viewer import (
    get_ra_viewer_status,
    get_ra_viewer_status_local,
    install_ra_viewer,
    install_ra_viewer_local,
    load_ra_viewer_config,
    load_ra_viewer_config_local,
    save_ra_viewer_config,
    save_ra_viewer_config_local,
    uninstall_ra_viewer,
    uninstall_ra_viewer_local,
)


__all__ = [
    "ScriptsStatus",

    "ensure_remote_scripts_dir",
    "ensure_local_scripts_dir",
    "ensure_update_all_config_bootstrap",
    "ensure_update_all_config_bootstrap_local",
    "check_update_all_initialized",
    "check_update_all_initialized_local",
    "get_scripts_status",
    "get_scripts_status_local",
    "open_scripts_folder_on_host",
    "open_scripts_folder_local",

    "install_update_all",
    "install_update_all_local",
    "uninstall_update_all",
    "uninstall_update_all_local",
    "run_update_all_stream",

    "get_zaparoo_update_status",
    "get_zaparoo_update_status_local",
    "install_zaparoo",
    "install_zaparoo_local",
    "enable_zaparoo_service",
    "enable_zaparoo_service_local",
    "disable_zaparoo_service_local",
    "uninstall_zaparoo",
    "uninstall_zaparoo_local",

    "install_migrate_sd",
    "install_migrate_sd_local",
    "uninstall_migrate_sd",
    "uninstall_migrate_sd_local",

    "install_cifs_mount",
    "install_cifs_mount_local",
    "uninstall_cifs_mount",
    "uninstall_cifs_mount_local",
    "run_cifs_mount",
    "run_cifs_umount",
    "remove_cifs_config",
    "remove_cifs_config_local",
    "load_cifs_config",
    "load_cifs_config_local",
    "save_cifs_config",
    "save_cifs_config_local",
    "test_cifs_connection",

    "install_auto_time",
    "install_auto_time_local",
    "uninstall_auto_time",
    "uninstall_auto_time_local",

    "install_cd_game_organizer",
    "install_cd_game_organizer_local",
    "uninstall_cd_game_organizer",
    "uninstall_cd_game_organizer_local",

    "install_dav_browser",
    "install_dav_browser_local",
    "uninstall_dav_browser",
    "uninstall_dav_browser_local",
    "load_dav_browser_config",
    "load_dav_browser_config_local",
    "save_dav_browser_config",
    "save_dav_browser_config_local",
    "remove_dav_browser_config",
    "remove_dav_browser_config_local",

    "install_ftp_save_sync",
    "install_ftp_save_sync_local",
    "uninstall_ftp_save_sync",
    "uninstall_ftp_save_sync_local",
    "load_ftp_save_sync_config",
    "load_ftp_save_sync_config_local",
    "save_ftp_save_sync_config",
    "save_ftp_save_sync_config_local",
    "remove_ftp_save_sync_config",
    "remove_ftp_save_sync_config_local",
    "enable_ftp_save_sync_service",
    "enable_ftp_save_sync_service_local",
    "disable_ftp_save_sync_service",
    "disable_ftp_save_sync_service_local",
    "ensure_ftp_save_sync_bootstrap",
    "ensure_ftp_save_sync_bootstrap_local",
    "is_ftp_save_sync_service_enabled",
    "is_ftp_save_sync_service_enabled_local",

    "install_static_wallpaper",
    "install_static_wallpaper_local",
    "uninstall_static_wallpaper",
    "uninstall_static_wallpaper_local",
    "remove_static_wallpaper",
    "remove_static_wallpaper_local",
    "list_static_wallpapers",
    "list_static_wallpapers_local",
    "get_static_wallpaper_preview_bytes",
    "get_static_wallpaper_preview_bytes_local",
    "apply_static_wallpaper",
    "apply_static_wallpaper_local",
    "reload_mister_menu",
    "is_static_wallpaper_active",
    "is_static_wallpaper_active_local",
    "has_static_wallpaper_saved_selection",
    "has_static_wallpaper_saved_selection_local",
    "get_static_wallpaper_saved_selection",
    "get_static_wallpaper_saved_selection_local",
    "get_static_wallpaper_state",
    "get_static_wallpaper_state_local",

    "install_syncthing",
    "install_syncthing_local",
    "uninstall_syncthing",
    "uninstall_syncthing_local",
    "get_syncthing_status",
    "get_syncthing_status_local",
    "start_syncthing",
    "stop_syncthing",
    "is_syncthing_running",
    "is_syncthing_start_on_boot_enabled",
    "is_syncthing_start_on_boot_enabled_local",
    "enable_syncthing_start_on_boot",
    "enable_syncthing_start_on_boot_local",
    "disable_syncthing_start_on_boot",
    "disable_syncthing_start_on_boot_local",
    "toggle_syncthing_start_on_boot",
    "toggle_syncthing_start_on_boot_local",

    "get_ra_viewer_status",
    "get_ra_viewer_status_local",
    "install_ra_viewer",
    "install_ra_viewer_local",
    "uninstall_ra_viewer",
    "uninstall_ra_viewer_local",
    "load_ra_viewer_config",
    "load_ra_viewer_config_local",
    "save_ra_viewer_config",
    "save_ra_viewer_config_local",
]